env:
  browser: true
  es2021: true
extends:
  - standard-with-typescript
  - plugin:lit/recommended
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "no-unused-vars": "off",
  "@typescript-eslint/no-unused-vars": [ "error", {
    "varsIgnorePattern": "^[A-Z][a-zA-Z]*$",
    "argsIgnorePattern": "^[A-Z][a-zA-Z]*$"
  }]
}
